'use client';
import { Alfa_Slab_One, Inter, Poppins } from 'next/font/google';
import './globals.css';
import Header from '../../components/Header/Header';
import React from 'react';
import { MainContextProvider } from '../contexts/ContextProvider/ContextProvider';
import { usePathname } from 'next/navigation';

const poppins = Poppins({ subsets: ['latin'], weight: ['500'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
// export const ContextProvider = React.createContext();

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <MainContextProvider>
      <html lang="en">
        <body className={poppins.className} style={{ margin: '0' }}>
          {pathname != '/login' && pathname != '/registration' ? <Header /> : <></>}
          {children}
        </body>
      </html>
    </MainContextProvider>
  );
}
