'use client';
import { Poppins } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import Header from '../components/Header/Header';
import React from 'react';
import ContactUs from '@/components/ContactUs/ContactUs';
import { MainContextProvider } from '../contexts/ContextProvider/ContextProvider';
import { usePathname, useParams } from 'next/navigation';
import { poppins } from '@/fonts';
import { UserProvider } from '@/contexts/authContext/authContext';

// const poppins = Poppins({ subsets: ['latin'], weight: ['500', '400', '900', '800', '700'] });
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
export const ContextProvider = React.createContext();
export default function RootLayout({ children, user, loading = false }) {
  const params = useParams();
  const pathname = usePathname();
  return (
    <UserProvider value={{ user, loading }}>
      <MainContextProvider>
        <html lang="en">
          <body
            className={poppins.className}
            style={{
              margin: '0',
              backgroundColor:
                pathname === '/orientation-page' ||
                pathname === '/orientation-page/quiz' ||
                pathname === '/orientation-page/recomendation' ||
                pathname === '/game'
                  ? '#A2BF00'
                  : 'initial',
            }}>
            <div className={styles.mainWrapper}>{children}</div>
          </body>
        </html>
      </MainContextProvider>
    </UserProvider>
  );
}
